#!/usr/bin/env bash

function print_help {
cat <<EOF
Description here
etc
EOF
}
 

case $1 in
    h) print_help ; exit ;;
esac

sudo apt install gdb-multiarch

sudo apt install doxygen doxygen-doc graphviz pulseview \
	cmake gcc-arm-none-eabi libnewlib-arm-none-eabi \
    texinfo libtool libhidapi-dev libusb-1.0-0-dev

echo "You prolly also want to install stlink and friends"


