#!/usr/bin/env bash

function print_help {
cat <<EOF
Description here
etc
EOF
}
 

case $1 in
    h) print_help ; exit ;;
esac

sudo apt install gdb-multiarch

sudo apt install doxygen doxygen-doc graphviz pulseview 

echo "You prolly also want to install stlink and friends"


