#!/usr/bin/env bash


function print_help {
cat <<EOF
Description here
etc
EOF
}
 

case $1 in
    h) print_help ; exit ;;
esac

#qemu-system-arm -M raspi0 -kernel kernel.img -serial telnet:127.0.0.1:4444,server,nowait
qemu-system-arm -M raspi0 -serial null -serial stdio -bios kernel.img
#-serial telnet:127.0.0.1:4444,server,nowait
#DRIVE="-drive file=$IMG,if=sd,format=raw"
KERNEL="-kernel kernel.img"
#KERNEL="-kernel ../fipq-kernel-qemuvpb.img"
#qemu-system-arm -machine versatilepb -cpu cortex-a8 -m 256M $DRIVE $KERNEL -serial stdio
