#!/usr/bin/env bash

The build is good, I think, but for some reason the serial isn't connecting

function print_help {
cat <<EOF
Description here
etc
EOF
}
 

case $1 in
    h) print_help ; exit ;;
esac

qemu-system-aarch64 -M raspi3 -kernel kernel8.img -serial stdio
