ARMGNU ?= arm-none-eabi

#ARMGNU ?= arm-none-eabi
#ARMGNU ?= arm-linux-gnueabihf
#CC = arm-linux-gnueabihf-gcc-8
#CC = aarch64-linux-gnu-gcc



//OBJS = homer.o

#OBJS = rpi-usb.o rpi-SmartStart.o SmartStart64.o
include ../../Germ7.mk

install:
	cp kernel7.img /media/pi/5794-CDC0
